{% set name = "pysjef" %}
{% set version = "1.45.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/molpro/sjef/archive/refs/tags/{{ version }}.tar.gz
  sha256: 079182dce5945eec596eb5fe857471ee074ff0c241f6619ef5b7600b7e0dacbc


build:
  script:
    - export SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}  # [unix]
    - {{ PYTHON }} -m pip install .
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython >=3.0                                 # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - cmake >=3.14
    - make
    - pkg-config
    - setuptools-scm >=8.1
    - setuptools >=64
    - libboost-headers >=1.88
    - pugixml >=1.10

  host:
    - python
    - pip
    - libboost-headers >=1.88
    - pugixml >=1.10
    - cython >=3.0
    - setuptools
    - setuptools-scm >=8.1
    - scikit-build-core >=0.10      # <<< ADDED: PEP 517 build backend required by pyproject.toml
    - scikit-build              # optional: add only if build logs later complain it is missing
  run:
    - python
    - lxml >=4.0
    - rsync  # [not win]
    - regex
    - numpy >=1.17
    - m2-base  # [win]

test:
  imports:
    - pysjef
    - pysjef.project
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/molpro/sjef
  summary: |
    Python Simple Job Execution Framework (Pysjef) is pronounced pie-chef
  description: A library that supports the running of any program asynchronously either locally, directly on a remote machine, or via a batch queueing system
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://molpro.github.io/pysjef
  dev_url: https://github.com/molpro/sjef

extra:
  recipe-maintainers:
    - pjknowles
    - molpro-owner
